### ISSUE TITLE
Theme contains nonexistent URLs that break Less compilation

### ISSUE THREAD

**Issue by GabiAxel** [syncfusion/JavaScript-Widgets#3]
In `default-theme/ej.theme.less`:

Line 2690: `/themes/common-images/Rotate.cur` and `../themes/common-images/Rotate.cur`

Line 5750: `../images/expand.png`

Line 5763: `../images/colapse.png`

I'm using npm+webpack to load css and less, and processing `ej.theme.less` fails because the URLs are not found. Only after removing these URLs the errors are gone.

**Comment by tyeth** [comment]
Similar issue myself with this in an asp.net project using vs2015+web-essentials.
It's a less compilation issue after bundling for me. 
I believe the images are higher up the path tree than the initial less file which isn't supported. 

Something about the master less file being further up the path tree solved if i remember correctly. 
So i made a master less file in site root and included the ej less files, sadly i broke it doing last update of syncfusion libraries.

**Comment by tyeth** [comment]
So it broke my icons because they've removed the e-icon class from buttons with images. 
My **Content** folder contains the **ej** folder.
My less file is /Content/ej.site.less and contains two lines:
    @import url("ej/web/ej.widgets.core.less");
    @import url("ej/web/gradient-azure/ej.theme.less");

**Comment by Sridhar-Narasimhan** [comment]
Version 15.1.33 solves this issue.
