### ISSUE TITLE
missing dependency?

### ISSUE THREAD

**Issue by bondarewicz** [syncfusion/JavaScript-Widgets#6]
just ran: `bower install syncfusion-javascript --save` and included `'ejangular'` in angular module dependencies as seen in the [docs](http://help.syncfusion.com/js/angularjs) 

Getting: `Module 'ejangular' is not available!`

Checked under `bower_components` and only got `ej.angular2.min.js`
<img width="271" alt="syncfusion" src="https://cloud.githubusercontent.com/assets/435051/16520251/d234f6fe-3f86-11e6-9c13-27f91392bae6.png">

bowser.json points to `"syncfusion-javascript": "^14.2.26"`
Could someone point me into the right direction here? Any help appreciated...

**Comment by karthickthangasamy** [comment]
@bondarewicz All the Essential JS for AngularJS directives have been encapsulated into a single module called `ejangular` and those are available in `ej.widget.angular.min.js`.

Help documentation : https://help.syncfusion.com/angularjs/overview
Sample browser : http://ngjq.syncfusion.com/

Thanks.
