### ISSUE TITLE
EJ Web bootstrap theme - LESS compilation error from unescaped IE hack

### ISSUE THREAD

**Issue by murraybiscuit** [syncfusion/JavaScript-Widgets#8]
**Description**: LESS compiler is throwing an exception due to unescaped IE hack.
**File**: /Content/ej/web/bootstrap-theme/ej.theme.less
**Line**: 1064
**Code**:   `border:@border-size @border-type @content-border-color \9;`

Other parts of this file have the hack correctly escaped (`~"\9"`).
Suggested fix:
 `border:@border-size @border-type @content-border-color~"\9";`
Patch and pull request in progress.

**Comment by murraybiscuit** [comment]
File patched. LESS compilation is resolved for me. Haven't tested output in <= IE 9

**Comment by Sridhar-Narasimhan** [comment]
Version 14.4.20 solves this issue.
